language: node_js
node_js: stable
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- export GIT_REPO=https://$REPO_TOKEN@github.com:sjfkai/mapLocation.git
install:
- yarn
script:
- yarn run publish
